### PR TITLE
Screenshot modification

### PR DESCRIPTION
**Pull request by SzymG**
Added functionality of screenshot modification

### CODE REVIEW

**Comment by WildaSoftware** [comment]
@SzymG thank you for your pull request :) I have following remarks (to code and functionality).

1. Color hexes used in SCSS should be stored in variables. It allows to keep standard in plugin styling. It is also applied to symbols (e.g. "red", "yellow") but in this case it is not obligatory to move them to variables.

2. Try to keep indentation values as similar to original as possible. It is difficult to track changes because of many indentation changes detected by Git.

3. js/feedybacky.js, line 168 - why "dot_flag" is written in snake case rather than camel case like other keys?

4. Maybe is it good idea to move event listeners related to modal to another function?

5. I think it is risky to set HTML identifiers like "blue", "green" etc. There is high probability that such nodes would not have unique IDs within a whole page. In general, all classes and identifiers in plugin should start with "feedybacky-".

6. "mycanvas" should be "myCanvas", but this is not a prority. But again - "can" identifier could "not unique enough" to be used on every site. It is also should be moved to constant.

7. Try to use single quotes instead of double quotes.

8. The parameter "res" for "findxyOnScreenshot" (by the way - "xy" should be capitals) is not self-explanatory. Maybe "action" or "eventType" would be better?

9. saveScreenshotModification - unnecessary console.log.

10. In README.md it should be described how to use a new function.

11. Screenshot method button should be visible only if the appropriate checkbox is checked. It should be centered, slightly bigger (if possible) and be placed under text area (before first checkbox). I suggest button label "Mark places" ("Zaznacz miejsca").

12. After clicking a "modify screenshot" button, it should be signalized (e.g. by spinner) that something is going on because now the browser freezes and a user can be worried.

12. If is is possible, the screenshot on the modal should not be narrowed (for "high" sites).

13. When I click "modify screenshot", make some modifications, click "Save" and one more time click "modify screenshot", the screenshot is processed again and my modifications are gone. Is is correct?

14. I checked off screenshot checkbox and still modify a screenshot. The screenshot was still sent - this is a bug. It seems that after modifying a screenshot is not possible to send a request without it without a page refresh.

15. I cleared my screenshot modifications but the plugin still sends some older modifications. Modifications on canvas should be cleared automatically after each request sending.

16. When the "mediaDevice" screenshot method is enabled, the screenshot is taken one more time just after send. It also seems a bug. If it is not possible to omit, the screenshot modification should be disabled for such screenshot taking method.

**Review by WildaSoftware — CHANGES_REQUESTED** [review]
My comments are here: https://github.com/WildaSoftware/Feedybacky/pull/3#issuecomment-932935258

**Comment by jrojek493** [comment]
Points fixed.

**Comment by WildaSoftware** [comment]
Points fixed.

**Pull request merged**
